baseURL = "http://localhost/"
ilanguageCode = "en-us"
title = "Tiips 博客"
theme = "hugo-swift-theme"
author = "Timo"
copyright = "Copyright © 2020, Timo Authors; all rights reserved."
#canonifyurls = true
paginate = 4
# use uglyurls to have filenames and these can be served in s3
uglyurls = true
[params]
  google_fonts = [
    ["Fira Code", "400, 700"],
    ["Open Sans", "400, 400i, 700, 700i"]
  ]

  heading_font = "Nunito"
  body_font = "Monsterrat"

disableLiveReload = true