baseURL = "http://localhost/"
languageCode = "en-us"
title = "Tiips 博客"
theme = "hugo-swift-theme"
author = "Timo"
copyright = "Copyright © 2020, Timo Authors; all rights reserved."
canonifyurls = true
paginate = 4
uglyurls = true
